version: "3.9"

services:
  # ───────── WebSocket Beacon ─────────
  beacon:
    build: .                       # uses beacon/Dockerfile
    container_name: arius-beacon
    env_file:
      - ./.env
    ports:
      - "3000:3000"                # host:container
    volumes:
      - .:/usr/src/app             # live‑reload during dev
    depends_on:
      - postgres

  # ───────── PostgreSQL ───────────
  postgres:
    image: postgres:16-alpine
    container_name: arius-postgres
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data      # persistent DB files
      - ./sql:/docker-entrypoint-initdb.d    # runs init.sql on first boot
    ports:
      - "5432:5432"              # optional; expose DB to host

volumes:
  pgdata:                          # named volume for Postgres data
